language: php

before_script:
  - sh -c "if [ 'hhvm' != '$(phpenv version-name)' ]; then 'extension=memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && echo 'memcached.so loaded'; fi"
  - composer install --prefer-source

services:
  - memcache

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

script: phpunit --strict
