before_script:
  - mysql -e 'CREATE DATABASE emyi-200-dev;'
  - psql  -c 'CREATE DATABASE emyi-200-dev;' -U postgres

services:
  - memcache

language: php
php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

script: phpunit --strict tests/
